
import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    calendar: 'Calendar',
    expenses: 'Expenses',
    reports: 'Reports',
    units: 'Units',
    settings: 'Settings',
    logout: 'Logout',
    totalActiveBookings: 'Active Bookings',
    netProfit: 'Net Profit',
    totalExpenses: 'Total Expenses',
    recentActivity: 'Recent Activity',
    monthlyRevenue: 'Monthly Revenue',
    addBooking: 'Add Booking',
    editBooking: 'Edit Booking',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    unit: 'Unit',
    tenant: 'Tenant',
    dates: 'Dates',
    status: 'Status',
    price: 'Price',
    nightlyRate: 'Base Nightly Rate',
    villageFee: 'Village Fee (Daily)',
    dailyTotal: 'Daily Total',
    grandTotal: 'Grand Total',
    nights: 'Nights',
    housekeeping: 'Housekeeping',
    deposit: 'Deposit',
    notes: 'Notes',
    welcomeAgain: 'Welcome Again',
    notWelcome: 'Not Welcome',
    confirmed: 'Confirmed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    paid: 'Paid',
    unpaid: 'Unpaid',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    signIn: 'Sign In',
    signUp: 'Create Account',
    haveAccount: 'Already have an account?',
    noAccount: 'Don\'t have an account?',
    email: 'Email',
    password: 'Password',
    generateReceipt: 'Generate Receipt',
    exportPDF: 'Export PDF',
    total: 'Total',
    subtotal: 'Subtotal',
    filterByUnit: 'Filter by Unit',
    filterByDate: 'Filter by Date',
    allUnits: 'All Units',
    addExpense: 'Add Expense',
    category: 'Category',
    amount: 'Amount',
    date: 'Date',
    unitType: 'Unit Type',
    actions: 'Actions',
    chalet: 'Chalet',
    villa: 'Villa',
    palace: 'Palace',
    currency: 'EGP',
    contact: 'Contact',
    fromDate: 'From',
    toDate: 'To',
    rentalOverview: 'Rental Overview',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    paymentStatus: 'Payment',
    editUnit: 'Edit Unit',
    unitName: 'Unit Name',
    addUnit: 'Add Unit',
    updateUnit: 'Update Unit',
    financialSummary: 'Financial Summary',
    financialSummaryDesc: 'Download net profit and revenue breakdown.',
    occupancyReport: 'Occupancy Report',
    occupancyReportDesc: 'Detailed view of unit usage and tenant history.',
    downloadPDF: 'Download PDF',
    snapshot: 'Snapshot',
    totalBookings: 'Total Bookings',
    totalUnits: 'Total Units',
    expenseRecords: 'Expense Records',
    today: 'Today',
    // Admin & Subscription
    adminDashboard: 'Admin Dashboard',
    accounts: 'Accounts',
    subscriptions: 'Subscriptions',
    addAccount: 'Add Account',
    fullName: 'Full Name',
    addSubscription: 'Add Subscription',
    durationDays: 'Duration (Days)',
    startDate: 'Start Date',
    subscriptionPrice: 'Subscription Price',
    daysRemaining: 'Days Remaining',
    subscriptionStatus: 'Subscription Status',
    active: 'Active',
    expired: 'Expired',
    paused: 'Paused',
    renew: 'Renew',
    subscriptionEnded: 'Subscription Ended',
    subscriptionEndedMsg: 'Your subscription has expired or is paused. You cannot add new data.',
    days: 'Days',
    printReceipt: 'Print Receipt',
    deleteSubscription: 'Delete Subscription',
    pauseSubscription: 'Pause Subscription',
    resumeSubscription: 'Resume Subscription',
    editSubscription: 'Edit Subscription',
    update: 'Update',
    clientSince: 'Client Since',
    // Admin Reports
    adminReports: 'System Reports',
    subscriptionReport: 'Subscriptions Report',
    subscriptionReportDesc: 'Comprehensive list of all clients, revenues, and statuses.',
    totalClients: 'Total Clients',
    totalRevenue: 'Total Revenue',
    revenue: 'Revenue'
  },
  ar: {
    dashboard: 'لوحة التحكم',
    bookings: 'الحجوزات',
    calendar: 'التقويم',
    expenses: 'المصروفات',
    reports: 'التقارير',
    units: 'الوحدات',
    settings: 'الإعدادات',
    logout: 'تسجيل خروج',
    totalActiveBookings: 'الحجوزات النشطة',
    netProfit: 'صافي الربح',
    totalExpenses: 'إجمالي المصروفات',
    recentActivity: 'النشاط الأخير',
    monthlyRevenue: 'الإيرادات الشهرية',
    addBooking: 'إضافة حجز',
    editBooking: 'تعديل حجز',
    delete: 'حذف',
    cancel: 'إلغاء',
    save: 'حفظ',
    unit: 'الوحدة',
    tenant: 'المستأجر',
    dates: 'التواريخ',
    status: 'الحالة',
    price: 'السعر',
    nightlyRate: 'سعر الليلة (الأساسي)',
    villageFee: 'رسوم القرية (يومي)',
    dailyTotal: 'إجمالي اليومي',
    grandTotal: 'الإجمالي النهائي',
    nights: 'الليالي',
    housekeeping: 'تنظيف',
    deposit: 'تأمين',
    notes: 'ملاحظات',
    welcomeAgain: 'مرحب به',
    notWelcome: 'غير مرحب به',
    confirmed: 'مؤكد',
    pending: 'قيد الانتظار',
    cancelled: 'ملغي',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    language: 'اللغة',
    theme: 'السمة',
    darkMode: 'الوضع الليلي',
    lightMode: 'الوضع النهاري',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    haveAccount: 'لديك حساب بالفعل؟',
    noAccount: 'ليس لديك حساب؟',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    generateReceipt: 'إصدار فاتورة',
    exportPDF: 'تصدير PDF',
    total: 'الإجمالي',
    subtotal: 'المجموع الفرعي',
    filterByUnit: 'تصفية حسب الوحدة',
    filterByDate: 'تصفية بالتاريخ',
    allUnits: 'كل الوحدات',
    addExpense: 'إضافة مصروف',
    category: 'الفئة',
    amount: 'المبلغ',
    date: 'التاريخ',
    unitType: 'نوع الوحدة',
    actions: 'إجراءات',
    chalet: 'شاليه',
    villa: 'فيلا',
    palace: 'قصر',
    currency: 'ج.م',
    contact: 'تواصل',
    fromDate: 'من',
    toDate: 'إلى',
    rentalOverview: 'نظرة عامة على الإيجارات',
    checkIn: 'دخول',
    checkOut: 'خروج',
    paymentStatus: 'الدفع',
    editUnit: 'تعديل الوحدة',
    unitName: 'اسم الوحدة',
    addUnit: 'إضافة وحدة',
    updateUnit: 'تحديث الوحدة',
    financialSummary: 'الملخص المالي',
    financialSummaryDesc: 'تحميل تفاصيل صافي الربح والإيرادات.',
    occupancyReport: 'تقرير الإشغال',
    occupancyReportDesc: 'عرض تفصيلي لاستخدام الوحدات وسجل المستأجرين.',
    downloadPDF: 'تحميل PDF',
    snapshot: 'لقطة سريعة',
    totalBookings: 'إجمالي الحجوزات',
    totalUnits: 'إجمالي الوحدات',
    expenseRecords: 'سجلات المصروفات',
    today: 'اليوم',
    // Admin
    adminDashboard: 'لوحة تحكم المسؤول',
    accounts: 'الحسابات',
    subscriptions: 'الاشتراكات',
    addAccount: 'إضافة حساب',
    fullName: 'الاسم الكامل',
    addSubscription: 'إضافة اشتراك',
    durationDays: 'المدة (أيام)',
    startDate: 'تاريخ البدء',
    subscriptionPrice: 'سعر الاشتراك',
    daysRemaining: 'الأيام المتبقية',
    subscriptionStatus: 'حالة الاشتراك',
    active: 'نشط',
    expired: 'منتهي',
    paused: 'موقوف مؤقتاً',
    renew: 'تجديد',
    subscriptionEnded: 'انتهى الاشتراك',
    subscriptionEndedMsg: 'اشتراكك منتهي أو موقوف مؤقتاً. لا يمكنك إضافة بيانات جديدة.',
    days: 'أيام',
    printReceipt: 'طباعة إيصال',
    deleteSubscription: 'حذف الاشتراك',
    pauseSubscription: 'إيقاف الاشتراك',
    resumeSubscription: 'استئناف الاشتراك',
    editSubscription: 'تعديل الاشتراك',
    update: 'تحديث',
    clientSince: 'عميل منذ',
    // Admin Reports
    adminReports: 'تقارير النظام',
    subscriptionReport: 'تقرير الاشتراكات',
    subscriptionReportDesc: 'قائمة شاملة بجميع العملاء، الإيرادات، وحالات الاشتراك.',
    totalClients: 'إجمالي العملاء',
    totalRevenue: 'إجمالي الإيرادات',
    revenue: 'الإيرادات'
  }
};

export const MOCK_UNITS = [];
export const MOCK_BOOKINGS = [];
export const MOCK_EXPENSES = [];
export const MOCK_USERS = [];
