import { Language } from './types';

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    bookings: 'Bookings',
    calendar: 'Calendar',
    expenses: 'Expenses',
    reports: 'Reports',
    units: 'Units',
    settings: 'Settings',
    logout: 'Logout',
    totalActiveBookings: 'Active Bookings',
    netProfit: 'Net Profit',
    totalExpenses: 'Total Expenses',
    recentActivity: 'Recent Activity',
    monthlyRevenue: 'Monthly Revenue',
    addBooking: 'Add Booking',
    editBooking: 'Edit Booking',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    unit: 'Unit',
    tenant: 'Tenant',
    dates: 'Dates',
    status: 'Status',
    price: 'Price',
    nightlyRate: 'Base Nightly Rate',
    villageFee: 'Village Fee (Daily)',
    dailyTotal: 'Daily Total',
    grandTotal: 'Grand Total',
    nights: 'Nights',
    housekeeping: 'Housekeeping',
    deposit: 'Deposit',
    notes: 'Notes',
    welcomeAgain: 'Welcome Again',
    notWelcome: 'Not Welcome',
    confirmed: 'Confirmed',
    pending: 'Pending',
    cancelled: 'Cancelled',
    paid: 'Paid',
    unpaid: 'Unpaid',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    signIn: 'Sign In',
    email: 'Email',
    password: 'Password',
    generateReceipt: 'Generate Receipt',
    exportPDF: 'Export PDF',
    total: 'Total',
    subtotal: 'Subtotal',
    filterByUnit: 'Filter by Unit',
    filterByDate: 'Filter by Date',
    allUnits: 'All Units',
    addExpense: 'Add Expense',
    category: 'Category',
    amount: 'Amount',
    date: 'Date',
    unitType: 'Unit Type',
    actions: 'Actions',
    chalet: 'Chalet',
    villa: 'Villa',
    palace: 'Palace',
    currency: 'EGP',
    contact: 'Contact',
    fromDate: 'From',
    toDate: 'To',
    rentalOverview: 'Rental Overview',
    checkIn: 'Check In',
    checkOut: 'Check Out',
    paymentStatus: 'Payment',
    editUnit: 'Edit Unit',
    unitName: 'Unit Name',
    addUnit: 'Add Unit',
    updateUnit: 'Update Unit',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    bookings: 'الحجوزات',
    calendar: 'التقويم',
    expenses: 'المصروفات',
    reports: 'التقارير',
    units: 'الوحدات',
    settings: 'الإعدادات',
    logout: 'تسجيل خروج',
    totalActiveBookings: 'الحجوزات النشطة',
    netProfit: 'صافي الربح',
    totalExpenses: 'إجمالي المصروفات',
    recentActivity: 'النشاط الأخير',
    monthlyRevenue: 'الإيرادات الشهرية',
    addBooking: 'إضافة حجز',
    editBooking: 'تعديل حجز',
    delete: 'حذف',
    cancel: 'إلغاء',
    save: 'حفظ',
    unit: 'الوحدة',
    tenant: 'المستأجر',
    dates: 'التواريخ',
    status: 'الحالة',
    price: 'السعر',
    nightlyRate: 'سعر الليلة (الأساسي)',
    villageFee: 'رسوم القرية (يومي)',
    dailyTotal: 'إجمالي اليومي',
    grandTotal: 'الإجمالي النهائي',
    nights: 'الليالي',
    housekeeping: 'تنظيف',
    deposit: 'تأمين',
    notes: 'ملاحظات',
    welcomeAgain: 'مرحب به',
    notWelcome: 'غير مرحب به',
    confirmed: 'مؤكد',
    pending: 'قيد الانتظار',
    cancelled: 'ملغي',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    language: 'اللغة',
    theme: 'السمة',
    darkMode: 'الوضع الليلي',
    lightMode: 'الوضع النهاري',
    signIn: 'تسجيل الدخول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    generateReceipt: 'إصدار فاتورة',
    exportPDF: 'تصدير PDF',
    total: 'الإجمالي',
    subtotal: 'المجموع الفرعي',
    filterByUnit: 'تصفية حسب الوحدة',
    filterByDate: 'تصفية بالتاريخ',
    allUnits: 'كل الوحدات',
    addExpense: 'إضافة مصروف',
    category: 'الفئة',
    amount: 'المبلغ',
    date: 'التاريخ',
    unitType: 'نوع الوحدة',
    actions: 'إجراءات',
    chalet: 'شاليه',
    villa: 'فيلا',
    palace: 'قصر',
    currency: 'ج.م',
    contact: 'تواصل',
    fromDate: 'من',
    toDate: 'إلى',
    rentalOverview: 'نظرة عامة على الإيجارات',
    checkIn: 'دخول',
    checkOut: 'خروج',
    paymentStatus: 'الدفع',
    editUnit: 'تعديل الوحدة',
    unitName: 'اسم الوحدة',
    addUnit: 'إضافة وحدة',
    updateUnit: 'تحديث الوحدة',
  }
};

export const MOCK_UNITS = [];
export const MOCK_BOOKINGS = [];
export const MOCK_EXPENSES = [];